language: node_js
node_js:
  - node

sudo: false

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set @zendesk:registry https://zdrepo.jfrog.io/zdrepo/api/npm/npm/
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:_password $ARTIFACTORY_PASSWORD
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:username $ARTIFACTORY_USERNAME
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:email $ARTIFACTORY_EMAIL
  - npm config set //zdrepo.jfrog.io/zdrepo/api/npm/npm/:always-auth true

install:
  - yarn

before_deploy:
  - npm config set _auth $ARTIFACTORY_API_KEY
  - npm config set email $ARTIFACTORY_EMAIL

script:
  - yarn test
