language: node_js

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install: yarn --frozen-lockfile

before_deploy:
  - export NODE_DEBUG=gh-pages
  - find demo -type l | xargs sed -i '' || true # convert symlinks to regular files
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

deploy:
  - provider: script
    script: scripts/gh-pages.js
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: scripts/publish.js
    skip_cleanup: true
    on:
      branch: master
